export const GET_PRODUCT_LIST_LOADING = 'GET_PRODUCT_LIST_LOADING';
export const GET_PRODUCT_LIST_SUCCESS = 'GET_PRODUCT_LIST_SUCCESS';
export const GET_PRODUCT_LIST_ERROR = 'GET_PRODUCT_LIST_ERROR';

export const GET_CATEGORY_LIST_LOADING = 'GET_CATEGORY_LIST_LOADING';
export const GET_CATEGORY_LIST_SUCCESS = 'GET_CATEGORY_LIST_SUCCESS';
export const GET_CATEGORY_LIST_ERROR = 'GET_CATEGORY_LIST_ERROR';

export const ADD_SEARCH_QUERY = 'ADD_SEARCH_QUERY';

export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const INCREASE_PRODUCT = 'INCREASE_PRODUCT';
export const DECREASE_PRODUCT = 'DECREASE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

